name: Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build --no-cache . --tag ghcr.io/etofi/homehub_docker:latest --tag ghcr.io/etofi/homehub_docker:$(git describe --tags --abbrev=0)
        docker push ghcr.io/etofi/homehub_docker:latest
        docker push ghcr.io/etofi/homehub_docker:$(git describe --tags --abbrev=0)
